<?php

$psxdb['regions'] = array(
	'A'  => 'Asia',
	'Ar' => 'Argentina',
	'At' => 'Austria',
	'Au' => 'Australia',
	'B'  => 'Brazil',
	'C'  => 'China',
	'Ca'  => 'Canada',
	'Cz' => 'Czech',
	'E'  => 'Europe',
	'EJ' => 'Europe, Japan',
	'F'  => 'France',
	'Fi' => 'Finland',
	'G'  => 'Germany',
	'Gr' => 'Greece',
	'H'  => 'Hungary',
	'I'  => 'Italy',
	'J'  => 'Japan',
	'K'  => 'Korea',
	'N'  => 'Netherlands',
	'P'  => 'Poland',
	'Pt' => 'Portugal',
	'R'  => 'Russia',
	'S'  => 'Spain',
	'Sk' => 'Slovakia',
	'Sw' => 'Sweden',
	'UK' => 'UK',
	'U'  => 'USA',
	'UE' => 'USA, Europe',
	'UJ' => 'USA, Japan',
	'Ua' => 'Ukraine',
	'W'  => 'World'
);

$psxdb['categories'] = array(
	 1 => 'Games',
	 2 => 'Demos',
	 3 => 'Video',
	 4 => 'Audio',
	 5 => 'Multimedia',
	 6 => 'Applications',
	 7 => 'Coverdiscs',
	 8 => 'Educational',
	 9 => 'Bonus Discs',
	10 => 'Betas'
);

$psxdb['languages'] = array('ara', 'cat', 'chi', 'cze', 'dan', 'dut', 'eng', 'fin', 'fre', 'ger', 'gre', 'hrv', 'hun', 'ita', 'jap', 'kor', 'nor', 'pol', 'por', 'rus', 'slk', 'spa', 'swe', 'tha');

$psxdb['languages_names'] = array(
	'ara' => 'Arabic',
	'cat' => 'Catalan',
	'chi' => 'Chinese',
	'hrv' => 'Croatian',
	'cze' => 'Czech',
	'dan' => 'Danish',
	'dut' => 'Dutch',
	'eng' => 'English',
	'fin' => 'Finnish',
	'fre' => 'French',
	'ger' => 'German',
	'gre' => 'Greek',
	'hun' => 'Hungarian',
	'ita' => 'Italian',
	'jap' => 'Japanese',
	'kor' => 'Korean',
	'nor' => 'Norwegian',
	'pol' => 'Polish',
	'por' => 'Portuguese',
	'rus' => 'Russian',
	'slk' => 'Slovak',
	'spa' => 'Spanish',
	'swe' => 'Swedish',
	'tha' => 'Thai'
);

$psxdb['languages_no-intro'] = array(
	'eng' => 'En',
	'jap' => 'Ja',
	'fre' => 'Fr',
	'ger' => 'De',
	'spa' => 'Es',
	'ita' => 'It',
	'dut' => 'Nl',
	'por' => 'Pt',
	'swe' => 'Sv',
	'nor' => 'Nn',
	'dan' => 'Da',
	'fin' => 'Fi',
	'kor' => 'Ko',
	'gre' => 'El',
	'pol' => 'Pl',
	'rus' => 'Ru',
	'chi' => 'Ch',
	'hrv' => 'Hr',
	'hun' => 'Hu',
	'cze' => 'Cs',
	'slk' => 'Sk',
	'ara' => 'Ar',
	'cat' => 'Ca',
	'tha' => 'Th'
);